import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Appearance, FlatList, Linking, Modal, Platform, Pressable, RefreshControl, SafeAreaView, ScrollView, StatusBar, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage'; import { Ionicons } from '@expo/vector-icons';

type Category = 'All'|'General AI'|'AI Research'|'AI Companies'|'AI Technology'|'AI Startups'|'AI Products'|'Global AI News'|'AI Business'|'AI Regulations'|'AI Science';
type News = { id:string; title:string; summary:string; category:Category; sourceName:string; sourceUrl:string; publishedAt:string; importanceScore:number; isMock?:boolean; coveredBy?:number };
type CompanyResponse = { company:string; updates:News[]; requestedCount:10; availabilityNote?:string };
const API = process.env.EXPO_PUBLIC_API_URL || (Platform.OS === 'android' ? 'http://10.0.2.2:4000' : 'http://localhost:4000');
const categories: Category[] = ['All','General AI','AI Research','AI Companies','AI Technology','AI Startups','AI Products','Global AI News','AI Business','AI Regulations','AI Science'];
const trends = ['AI Agents','Robotics','AI Coding','AI Startups','AI Regulation','Generative AI'];
const fmt = (d:string) => new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(d));

export default function App() {
 const [news,setNews]=useState<News[]>([]), [loading,setLoading]=useState(true), [refreshing,setRefreshing]=useState(false), [query,setQuery]=useState(''), [category,setCategory]=useState<Category>('All'), [saved,setSaved]=useState<News[]>([]), [savedOpen,setSavedOpen]=useState(false), [dark,setDark]=useState(Appearance.getColorScheme()==='dark'), [settings,setSettings]=useState(false), [company,setCompany]=useState(''), [companyResult,setCompanyResult]=useState<CompanyResponse|null>(null), [companyLoading,setCompanyLoading]=useState(false), [error,setError]=useState('');
 const colors = dark ? {bg:'#080D18',card:'#111A2B',text:'#F6F8FC',muted:'#96A1B8',accent:'#61A7FF',line:'#26334B',chip:'#1A2940'} : {bg:'#F5F7FB',card:'#FFFFFF',text:'#11203B',muted:'#68738A',accent:'#276EF1',line:'#E3E8F1',chip:'#EAF1FF'};
 const load = useCallback(async (force=false) => { try { setError(''); if(force) await fetch(`${API}/refresh-news`,{method:'POST'}); const r=await fetch(`${API}/news?category=${encodeURIComponent(category)}&q=${encodeURIComponent(query)}`); if(!r.ok) throw Error(); const data=await r.json(); setNews(data); } catch { setError('Unable to load AI updates. Check your connection and API address.'); } finally {setLoading(false);setRefreshing(false);} },[category,query]);
 useEffect(()=>{ load(); },[load]); useEffect(()=>{AsyncStorage.getItem('bookmarks').then(v=>v&&setSaved(JSON.parse(v)));},[]);
 const toggleSave=async (n:News)=>{const next=saved.some(x=>x.id===n.id)?saved.filter(x=>x.id!==n.id):[n,...saved];setSaved(next);await AsyncStorage.setItem('bookmarks',JSON.stringify(next));};
 const companySearch=async()=>{if(!company.trim())return;setCompanyLoading(true); try{const r=await fetch(`${API}/company/${encodeURIComponent(company.trim())}/updates`);setCompanyResult(await r.json());}catch{Alert.alert('No connection','Company updates could not be loaded.');}finally{setCompanyLoading(false);}};
 const mock = news.some(n=>n.isMock); const breaking=news[0]; const visible=useMemo(()=>news.slice(1),[news]);
 const Card=({item,breakingCard=false}:{item:News;breakingCard?:boolean})=><View style={[styles.card,{backgroundColor:colors.card,borderColor:breakingCard?'#FF866B':colors.line}]}><View style={styles.cardTop}><View><Text style={[styles.category,{color:colors.accent}]}>{breakingCard?'🚨 BREAKING AI NEWS':`✦ ${item.category}`}</Text><Text style={[styles.headline,{color:colors.text}]}>{item.title}</Text></View><Pressable accessibilityLabel="Save update" onPress={()=>toggleSave(item)}><Ionicons name={saved.some(x=>x.id===item.id)?'bookmark':'bookmark-outline'} size={23} color={colors.accent}/></Pressable></View><Text style={[styles.summary,{color:colors.muted}]}><Text style={{fontWeight:'700'}}>AI Summary: </Text>{item.summary}</Text><Text style={[styles.source,{color:colors.muted}]}>Source: {item.sourceName} · {fmt(item.publishedAt)}{item.coveredBy&&item.coveredBy>1?` · Covered by ${item.coveredBy} sources`:''}</Text><Pressable onPress={()=>Linking.openURL(item.sourceUrl)} style={styles.read}><Text style={{color:colors.accent,fontWeight:'800'}}>🔗 Read Full Article</Text></Pressable></View>;
 return <SafeAreaView style={[styles.safe,{backgroundColor:colors.bg}]}><StatusBar barStyle={dark?'light-content':'dark-content'}/><FlatList data={visible} keyExtractor={x=>x.id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load(true);}} tintColor={colors.accent}/>} ListHeaderComponent={<>
 <View style={styles.header}><View><Text style={[styles.brand,{color:colors.text}]}>AI WORLD DAILY</Text><Text style={[styles.subtitle,{color:colors.muted}]}>Your daily AI updates from around the world.</Text><Text style={[styles.time,{color:colors.muted}]}>{new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})} · Updated now</Text></View><Pressable style={[styles.iconButton,{backgroundColor:colors.card}]} onPress={()=>{setRefreshing(true);load(true);}}><Ionicons name="refresh" color={colors.accent} size={22}/></Pressable></View>
 {mock&&<View style={styles.notice}><Text style={styles.noticeText}>Development data — no live RSS feed could be reached. Configure trusted feeds before release.</Text></View>}
 <View style={[styles.search,{backgroundColor:colors.card,borderColor:colors.line}]}><Ionicons name="search" color={colors.muted} size={20}/><TextInput value={query} onChangeText={setQuery} placeholder="Search AI news, products, or topics" placeholderTextColor={colors.muted} style={[styles.input,{color:colors.text}]}/></View>
 <Text style={[styles.section,{color:colors.text}]}>🔥 Trending in AI</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{trends.map(t=><Pressable key={t} onPress={()=>setQuery(t)} style={[styles.chip,{backgroundColor:colors.chip}]}><Text style={{color:colors.accent,fontWeight:'700'}}>{t}</Text></Pressable>)}</ScrollView>
 <Text style={[styles.section,{color:colors.text}]}>🔎 AI Company Updates</Text><View style={styles.companyRow}><TextInput value={company} onChangeText={setCompany} onSubmitEditing={companySearch} placeholder="Search company AI updates..." placeholderTextColor={colors.muted} style={[styles.companyInput,{color:colors.text,backgroundColor:colors.card,borderColor:colors.line}]}/><Pressable onPress={companySearch} style={[styles.go,{backgroundColor:colors.accent}]}>{companyLoading?<ActivityIndicator color="#fff"/>:<Ionicons name="arrow-forward" color="#fff" size={20}/>}</Pressable></View>
 {breaking&&<Card item={breaking} breakingCard/>}
 <Text style={[styles.section,{color:colors.text}]}>📂 Category filters</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.chips}>{categories.map(c=><Pressable key={c} onPress={()=>setCategory(c)} style={[styles.chip,{backgroundColor:category===c?colors.accent:colors.chip}]}><Text style={{color:category===c?'#fff':colors.accent,fontWeight:'700'}}>{c}</Text></Pressable>)}</ScrollView>
 <Text style={[styles.section,{color:colors.text}]}>🌍 TODAY'S TOP AI UPDATES</Text>
 {loading&&<ActivityIndicator color={colors.accent} style={{margin:24}}/>}{error?<Pressable onPress={()=>load()} style={styles.error}><Text>{error} Tap to retry.</Text></Pressable>:null}{!loading&&!error&&!news.length&&<View style={[styles.empty,{backgroundColor:colors.card,borderColor:colors.line}]}><Text style={[styles.emptyTitle,{color:colors.text}]}>No updates in this category yet</Text><Text style={{color:colors.muted,textAlign:'center'}}>Try another category or refresh to load more source-backed AI news.</Text></View>}
 </>} renderItem={({item})=><Card item={item}/>} ListFooterComponent={<><Pressable onPress={()=>setSavedOpen(!savedOpen)} style={[styles.collapsible,{backgroundColor:colors.card}]}><Text style={[styles.section,{color:colors.text,marginBottom:0}]}>🔖 Saved Updates ({saved.length})</Text><Ionicons name={savedOpen?'chevron-up':'chevron-down'} color={colors.muted} size={20}/></Pressable>{savedOpen&&saved.map(n=><Card item={n} key={`saved-${n.id}`}/>)}<Pressable onPress={()=>setSettings(true)} style={[styles.collapsible,{backgroundColor:colors.card,marginBottom:30}]}><Text style={[styles.section,{color:colors.text,marginBottom:0}]}>⚙️ Settings</Text><Ionicons name="settings-outline" color={colors.muted} size={20}/></Pressable></>}/>
 <Modal visible={!!companyResult} animationType="slide" transparent onRequestClose={()=>setCompanyResult(null)}><View style={styles.modalBack}><View style={[styles.sheet,{backgroundColor:colors.bg}]}><View style={[styles.handle,{backgroundColor:colors.line}]}/><View style={styles.sheetHead}><Text style={[styles.sheetTitle,{color:colors.text}]}>{companyResult?.company} — Latest AI Updates</Text><Pressable onPress={()=>setCompanyResult(null)}><Ionicons name="close" color={colors.text} size={27}/></Pressable></View><ScrollView>{companyResult?.updates.map((u,i)=><View key={u.id} style={[styles.update,{borderColor:colors.line}]}><Text style={[styles.bullet,{color:colors.accent}]}>{i+1}.</Text><View style={{flex:1}}><Text style={{color:colors.text,fontWeight:'700'}}>{u.title}</Text><Text style={{color:colors.muted,marginTop:4}}>{u.summary}</Text><Pressable onPress={()=>Linking.openURL(u.sourceUrl)}><Text style={{color:colors.accent,marginTop:5,fontWeight:'700'}}>Source: {u.sourceName} ↗</Text></Pressable></View></View>)}{Array.from({length:Math.max(0,10-(companyResult?.updates.length||0))}).map((_,i)=><Text key={i} style={[styles.unavailable,{color:colors.muted}]}>{(companyResult?.updates.length||0)+i+1}. No reliable source-backed update available.</Text>)}{!!companyResult?.availabilityNote&&<Text style={[styles.note,{color:colors.muted}]}>{companyResult.availabilityNote}</Text>}</ScrollView></View></View></Modal>
 <Modal visible={settings} animationType="slide" transparent onRequestClose={()=>setSettings(false)}><View style={styles.modalBack}><View style={[styles.sheet,{backgroundColor:colors.bg}]}><View style={[styles.handle,{backgroundColor:colors.line}]}/><Text style={[styles.sheetTitle,{color:colors.text}]}>Settings</Text><View style={styles.setting}><View><Text style={{color:colors.text,fontWeight:'700'}}>Dark mode</Text><Text style={{color:colors.muted}}>Choose your reading theme</Text></View><Switch value={dark} onValueChange={setDark}/></View><Text style={[styles.settingLabel,{color:colors.text}]}>Notifications</Text><Text style={{color:colors.muted}}>Daily and breaking-news push notifications require a production push provider. The app currently keeps this disabled until configured.</Text><Pressable onPress={()=>setSettings(false)} style={[styles.done,{backgroundColor:colors.accent}]}><Text style={{color:'#fff',fontWeight:'800'}}>Done</Text></Pressable></View></View></Modal>
 </SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1},header:{padding:20,paddingBottom:12,flexDirection:'row',justifyContent:'space-between'},brand:{fontSize:25,fontWeight:'900',letterSpacing:.4},subtitle:{marginTop:4,fontSize:14},time:{marginTop:8,fontSize:12},iconButton:{width:44,height:44,borderRadius:14,alignItems:'center',justifyContent:'center'},notice:{marginHorizontal:16,padding:11,borderRadius:12,backgroundColor:'#FFF0CC'},noticeText:{color:'#754800',fontSize:12,fontWeight:'600'},search:{margin:16,marginBottom:8,height:50,borderWidth:1,borderRadius:15,paddingHorizontal:14,flexDirection:'row',alignItems:'center'},input:{flex:1,marginLeft:9,fontSize:15},section:{fontSize:16,fontWeight:'900',marginLeft:16,marginTop:18,marginBottom:9},chips:{paddingHorizontal:16,gap:8},chip:{paddingHorizontal:13,paddingVertical:9,borderRadius:999},companyRow:{flexDirection:'row',marginHorizontal:16,gap:8},companyInput:{flex:1,borderWidth:1,borderRadius:14,paddingHorizontal:14,height:48},go:{width:48,borderRadius:14,alignItems:'center',justifyContent:'center'},card:{borderWidth:1,borderRadius:18,padding:16,marginHorizontal:16,marginTop:12,shadowColor:'#001',shadowOpacity:.06,shadowRadius:10,elevation:1},cardTop:{flexDirection:'row',justifyContent:'space-between',gap:12},category:{fontSize:12,fontWeight:'900',marginBottom:7},headline:{fontSize:17,fontWeight:'900',lineHeight:22,flexShrink:1},summary:{fontSize:14,lineHeight:20,marginTop:12},source:{fontSize:12,marginTop:13},read:{marginTop:12},collapsible:{marginHorizontal:16,marginTop:12,padding:17,borderRadius:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},error:{margin:16,padding:13,borderRadius:12,backgroundColor:'#FFE5E0'},empty:{margin:16,padding:24,borderWidth:1,borderRadius:16,alignItems:'center'},emptyTitle:{fontSize:16,fontWeight:'800',marginBottom:7},modalBack:{flex:1,backgroundColor:'#0009',justifyContent:'flex-end'},sheet:{maxHeight:'86%',borderTopLeftRadius:25,borderTopRightRadius:25,padding:20},handle:{height:5,width:44,alignSelf:'center',borderRadius:99,marginBottom:15},sheetHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},sheetTitle:{fontSize:20,fontWeight:'900',flex:1},update:{flexDirection:'row',gap:10,paddingVertical:14,borderBottomWidth:1},bullet:{fontWeight:'900',fontSize:16},unavailable:{paddingVertical:11,fontStyle:'italic'},note:{marginTop:15,lineHeight:19},setting:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:24},settingLabel:{fontWeight:'900',fontSize:16,marginTop:26,marginBottom:6},done:{alignItems:'center',padding:14,borderRadius:14,marginTop:28}});
